#!/usr/bin/env perl
use strict;
use warnings;
use File::Path qw(mkpath);

print "nargs = $#ARGV\n";
my $GA_DOC_DIR = "./";
my $GA_API_DOC = "ga_api.tex";
my $GA_API_DIR = "./tmp/";
if ($#ARGV == 0) {
    $GA_API_DIR = "$ARGV[0]/";
}
mkpath $GA_API_DIR;

my $API_DECS = "\\documentclass\[12pt\]\{article\}\n";
$API_DECS .= "\\usepackage\{fullpage\}\n";
$API_DECS .= "\\usepackage\{color\}\n";
$API_DECS .= "\\usepackage\{alltt\}\n";
$API_DECS .= "\\usepackage\{underscore\}\n";
$API_DECS .= "\\usepackage\{environ\}\n";
$API_DECS .= "\\usepackage\{graphicx\}\n";
$API_DECS .= "\\include\{preamble\}\n";
$API_DECS .= "\\include\{otype\}\n\n";

my %apis = ();
my $key = "";
my $entry = "";
my $begin = 0;

# Parse infile and divide API documentation into individual entries
open(INFILE, "$GA_DOC_DIR/$GA_API_DOC") or die "couldn't open infile";
while(<INFILE>) {
  my $line = $_;
  if ($line =~ /\\apih\{([^\}]*)\}/) {
    $begin = 1;
    if ($entry) {
      $apis{$key} = $entry;
    }
    # make api name lowercase and spaces replaced with dashes
    $key = $1;
    unless($key) {
      die "key was empty for line '$line'";
    }
    $key =~ s/ /\-/g;
    $key = lc($key);
    $entry = $line;
  } elsif ($line =~ /\\end\{document\}/) {
    if ($entry) {
      $apis{$key} = $entry;
    }
  } elsif ($begin == 1) {
    $entry .= $line;
  }
}
close(INFILE);

foreach my $key (keys %apis)
{
  my $api_doc = $API_DECS;
  $api_doc .= "\\begin\{document\}\n\n";
  $api_doc .= $apis{$key};
  $api_doc .= "\\end\{document\}\n";
  my $api_file = "$key.tex";
  open(OUTFILE, ">$GA_API_DIR$api_file") or die "couldn't open outfile";
  print OUTFILE "$api_doc";
  close(OUTFILE);
}
