#!/usr/bin/env perl

$GA_DOC_DIR = "./";
$GA_API_DOC = "ga_api_FR.tex";

$API_DECS = "\\documentclass\[12pt\]\{article\}\n";
$API_DECS .= "\\usepackage\{fullpage\}\n";
$API_DECS .= "\\usepackage\{color\}\n";
$API_DECS .= "\\usepackage\{alltt\}\n";
$API_DECS .= "\\usepackage\{underscore\}\n";
$API_DECS .= "\\usepackage\{environ\}\n";
$API_DECS .= "\\usepackage\{graphicx\}\n";
$API_DECS .= "\\include\{preamble\}\n";
$API_DECS .= "\\include\{otype\}\n\n";

open(INFILE, "$GA_DOC_DIR/$GA_API_DOC");

$begin = 0;
%apis = {};

# Parse infile and divide API documentation into individual entries

while(<INFILE>) {
  $line = $_;
  if ($line =~ /\\apih\{(.*)\}/) {
    if ($begin == 1) {
      $apis{$key} = $entry;
    }
    $key = $1;
    $entry = "";
    $entry = $line;
    $begin = 1;
  } else {
    if ($begin == 1) {
      if (!($line =~ /\\end\{document\}/)) { 
        $entry .= $line;
      } else {
        $begin = 0;
      }
    }
  }
}

close(INFILE);

# Create a sorted list of keys

@keys = sort{ $apis{$a} cmp $apis{$b} } keys %apis;

$length = @keys;

# It looks like first entry in @keys is bogus, so start at 1

for ($i=1; $i<$length; $i++) {
  $api_doc = "";
  $api_doc = $API_DECS;
  $api_doc .= "\\begin\{document\}\n\n";
  $api_doc .= $apis{$keys[$i]};
  $api_doc .= "\\end\{document\}\n";
 
  $api_file = "$keys[$i].tex";
  print "$api_file\n\n";
  print "$api_doc\n";
  
}
